# Generated by Django 4.1.7 on 2023-04-06 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_password1_user_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password1',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password2',
            new_name='password_confirmation',
        ),
    ]
