# Generated by Django 4.1.7 on 2023-06-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Name'),
        ),
    ]
